/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AtomisticVisualizationDataMetadata } from './atomisticVisualizationDataMetadata';
import type { AtomisticVisualizationDataSimulationMode } from './atomisticVisualizationDataSimulationMode';
import type { PKAFrameMetric } from './pKAFrameMetric';

export interface AtomisticVisualizationData {
  positions: number[][];
  numbers: number[];
  symbols?: string[] | null;
  pbc?: boolean[] | [boolean, boolean, boolean] | null;
  metadata?: AtomisticVisualizationDataMetadata;
  initial_positions?: number[][] | null;
  final_positions?: number[][] | null;
  energies?: number[] | null;
  cell?: number[][] | null;
  trajectory?: number[][][] | null;
  vacancy_positions?: number[][] | null;
  interstitial_positions?: number[][] | null;
  n_defects?: number | null;
  interstitials?: number | null;
  pka_index?: number | null;
  frame_metrics?: PKAFrameMetric[] | null;
  simulation_mode?: AtomisticVisualizationDataSimulationMode;
}
