/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AtomisticVisualizationDataSimulationMode = typeof AtomisticVisualizationDataSimulationMode[keyof typeof AtomisticVisualizationDataSimulationMode] | null;


export const AtomisticVisualizationDataSimulationMode = {
  pka: 'pka',
  relax: 'relax',
  single_point: 'single_point',
  nvt: 'nvt',
} as const;
