/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ChartVisualizationMark = typeof ChartVisualizationMark[keyof typeof ChartVisualizationMark];


export const ChartVisualizationMark = {
  bar: 'bar',
  line: 'line',
  scatter: 'scatter',
} as const;
