/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ChartEncoding } from './chartEncoding';
import type { ChartVisualizationMark } from './chartVisualizationMark';
import type { ChartVisualizationRowsItem } from './chartVisualizationRowsItem';

export interface ChartVisualization {
  /**
     * @minLength 1
     * @maxLength 100
     * @pattern ^[A-Za-z0-9][A-Za-z0-9_-]*$
     */
  id: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  title: string;
  description?: string | null;
  source_node?: string | null;
  kind?: 'chart.v1';
  mark: ChartVisualizationMark;
  /**
     * @minItems 1
     * @maxItems 10000
     */
  rows: ChartVisualizationRowsItem[];
  x: ChartEncoding;
  y: ChartEncoding;
}
