/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ChartEncodingType } from './chartEncodingType';

export interface ChartEncoding {
  /**
     * @minLength 1
     * @maxLength 100
     */
  field: string;
  label?: string | null;
  type: ChartEncodingType;
  unit?: string | null;
}
