/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ChartEncodingType = typeof ChartEncodingType[keyof typeof ChartEncodingType];


export const ChartEncodingType = {
  quantitative: 'quantitative',
  nominal: 'nominal',
  ordinal: 'ordinal',
} as const;
