/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type DagNodeType = typeof DagNodeType[keyof typeof DagNodeType];


export const DagNodeType = {
  FETCH: 'FETCH',
  ALLOY: 'ALLOY',
  SIMULATE: 'SIMULATE',
  SWEEP: 'SWEEP',
  SCRIPT: 'SCRIPT',
} as const;
