/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DagNodeParams } from './dagNodeParams';
import type { DagNodeType } from './dagNodeType';

export interface DagNode {
  /**
     * @minLength 1
     * @maxLength 100
     * @pattern ^[A-Za-z0-9][A-Za-z0-9_-]*$
     */
  id: string;
  type: DagNodeType;
  depends_on?: string | string[] | null;
  params?: DagNodeParams;
}
