/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ExperimentResultsResponseNodeStatuses = {[key: string]: 'COMPLETE' | 'QUEUED' | 'RUNNING' | 'REVIEW' | 'FAILED' | 'BLOCKED' | 'NOT_RUN'};
