/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ExperimentResultsResponseErrors } from './experimentResultsResponseErrors';
import type { ExperimentResultsResponseMetrics } from './experimentResultsResponseMetrics';
import type { ExperimentResultsResponseNodeModelInfo } from './experimentResultsResponseNodeModelInfo';
import type { ExperimentResultsResponseNodeStatuses } from './experimentResultsResponseNodeStatuses';
import type { ExperimentResultsResponseStatus } from './experimentResultsResponseStatus';
import type { HypothesisEval } from './hypothesisEval';
import type { ModelMetadata } from './modelMetadata';

/**
 * Stable, permissive result shape for the experiment bundle endpoint.
 */
export interface ExperimentResultsResponse {
  experiment_id: string;
  status: ExperimentResultsResponseStatus;
  metrics: ExperimentResultsResponseMetrics;
  hypotheses: HypothesisEval[];
  node_statuses?: ExperimentResultsResponseNodeStatuses;
  model_info: ModelMetadata;
  node_model_info: ExperimentResultsResponseNodeModelInfo;
  summary: string;
  errors: ExperimentResultsResponseErrors;
}
