/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ExperimentResultsResponseStatus = typeof ExperimentResultsResponseStatus[keyof typeof ExperimentResultsResponseStatus];


export const ExperimentResultsResponseStatus = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  PARTIAL: 'PARTIAL',
} as const;
