/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ModelMetadata } from './modelMetadata';

export type ExperimentResultsResponseNodeModelInfo = {[key: string]: ModelMetadata};
