/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ExperimentBundleResponseScriptResults } from './experimentBundleResponseScriptResults';
import type { ExperimentResultsResponse } from './experimentResultsResponse';
import type { ExperimentSpec } from './experimentSpec';
import type { ScientificDecision } from './scientificDecision';
import type { SweepResultsReference } from './sweepResultsReference';
import type { VisualizationCatalogReference } from './visualizationCatalogReference';

export interface ExperimentBundleResponse {
  results: ExperimentResultsResponse;
  spec: ExperimentSpec;
  scientific_decision: ScientificDecision;
  analysis?: unknown | null;
  visualization_catalog_ref?: VisualizationCatalogReference | null;
  sweep_results_ref?: SweepResultsReference | null;
  script_results?: ExperimentBundleResponseScriptResults;
}
