/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DagNode } from './dagNode';
import type { Hypothesis } from './hypothesis';

export interface ExperimentSpec {
  /**
     * @minLength 1
     * @maxLength 100
     * @pattern ^[A-Za-z0-9][A-Za-z0-9_-]*$
     */
  experiment_id: string;
  /**
     * @minItems 1
     * @maxItems 128
     */
  dag: DagNode[];
  hypotheses?: Hypothesis[];
  decision_node_id?: string | null;
  parent_experiment_id?: string | null;
  /**
     * @minimum 0
     * @maximum 1000
     */
  revision?: number;
  change_summary?: string | null;
  force_recompute?: boolean;
  script_snapshot_id?: string | null;
}
