/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface Hypothesis {
  /**
     * @minLength 1
     * @maxLength 100
     * @pattern ^[A-Za-z0-9][A-Za-z0-9_-]*$
     */
  id: string;
  /**
     * @minLength 1
     * @maxLength 100
     * @pattern ^[A-Za-z0-9][A-Za-z0-9_-]*$
     */
  target_node: string;
  metric?: string;
  /**
     * @minLength 1
     * @maxLength 1000
     */
  assertion?: string;
}
