/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { HypothesisEvalReviewReason } from './hypothesisEvalReviewReason';
import type { HypothesisEvalStatus } from './hypothesisEvalStatus';

export interface HypothesisEval {
  id: string;
  status: HypothesisEvalStatus;
  metric: string;
  value: string;
  target_node?: string;
  sample_size?: number;
  ci_low?: number | null;
  ci_high?: number | null;
  review_reason?: HypothesisEvalReviewReason;
  detail?: string | null;
}
