/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type HypothesisEvalStatus = typeof HypothesisEvalStatus[keyof typeof HypothesisEvalStatus];


export const HypothesisEvalStatus = {
  PASSED: 'PASSED',
  REVIEW: 'REVIEW',
  FAILED: 'FAILED',
} as const;
