/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type HypothesisEvalReviewReason = typeof HypothesisEvalReviewReason[keyof typeof HypothesisEvalReviewReason] | null;


export const HypothesisEvalReviewReason = {
  MISSING_METRIC: 'MISSING_METRIC',
  INVALID_EXPRESSION: 'INVALID_EXPRESSION',
  NON_NUMERIC_VALUE: 'NON_NUMERIC_VALUE',
  INSUFFICIENT_SAMPLES: 'INSUFFICIENT_SAMPLES',
  EVALUATION_ERROR: 'EVALUATION_ERROR',
} as const;
