/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ModelMetadata {
  name?: string;
  version?: string;
  checkpoint?: string | null;
  checkpoint_sha256?: string | null;
  head?: string | null;
  dtype?: string | null;
  hardware?: string | null;
  device?: string;
}
