/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { NVTResultBondAngleStats } from './nVTResultBondAngleStats';
import type { NVTResultBondDistanceStats } from './nVTResultBondDistanceStats';
import type { NVTResultRdfStats } from './nVTResultRdfStats';

export interface NVTResult {
  seed: number;
  runtime_ms?: number | null;
  initial_positions?: number[][] | null;
  final_positions?: number[][] | null;
  atomic_numbers?: number[] | null;
  energies?: number[] | null;
  trajectory?: number[][][] | null;
  trajectory_stride?: number | null;
  trajectory_total_steps?: number | null;
  trajectory_truncated?: boolean;
  cell: number[][];
  pbc?: boolean[] | [boolean, boolean, boolean] | null;
  potential_energy: number;
  mean_temperature_K: number;
  std_temperature_K: number;
  max_force: number;
  n_frames: number;
  stable: boolean;
  analysis_applicable?: boolean;
  trajectory_quality_passed?: boolean;
  bond_distance_stats: NVTResultBondDistanceStats;
  bond_angle_stats: NVTResultBondAngleStats;
  rdf_stats: NVTResultRdfStats;
  positions: number[][];
}
