/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface PKAFrameMetric {
  /** @minimum 0 */
  frame: number;
  /** @minimum 0 */
  step: number;
  /** @minimum 0 */
  time_fs: number;
  /** @minimum 0 */
  kinetic_energy_ev: number;
  potential_energy_ev: number;
  /** @minimum 0 */
  temperature_K: number;
  /** @minimum 0 */
  n_defects: number;
  /** @minimum 0 */
  interstitials: number;
  /** @minimum 0 */
  displaced_atoms: number;
  /** @minimum 0 */
  max_displacement_angstrom: number;
  vacancy_positions?: number[][];
  interstitial_positions?: number[][];
}
