/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PKAFrameMetric } from './pKAFrameMetric';

export interface PKAResult {
  seed: number;
  runtime_ms?: number | null;
  initial_positions?: number[][] | null;
  final_positions?: number[][] | null;
  atomic_numbers?: number[] | null;
  energies?: number[] | null;
  trajectory?: number[][][] | null;
  trajectory_stride?: number | null;
  trajectory_total_steps?: number | null;
  trajectory_truncated?: boolean;
  cell?: number[][] | null;
  pbc?: boolean[] | [boolean, boolean, boolean] | null;
  n_defects: number;
  interstitials?: number | null;
  vacancy_positions?: number[][] | null;
  interstitial_positions?: number[][] | null;
  pka_index?: number | null;
  frame_metrics?: PKAFrameMetric[] | null;
  energy: number;
  scientific_status?: 'EXPERIMENTAL_UNVALIDATED';
}
