/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface RelaxResult {
  seed: number;
  runtime_ms?: number | null;
  initial_positions?: number[][] | null;
  final_positions?: number[][] | null;
  atomic_numbers?: number[] | null;
  energies?: number[] | null;
  trajectory?: number[][][] | null;
  trajectory_stride?: number | null;
  trajectory_total_steps?: number | null;
  trajectory_truncated?: boolean;
  cell: number[][];
  pbc?: boolean[] | [boolean, boolean, boolean] | null;
  potential_energy: number;
  max_force: number;
  force_norm: number;
  positions: number[][];
}
