/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RunRecordResponseState } from './runRecordResponseState';

/**
 * Stable API representation with no omitted defaulted fields.
 */
export interface RunRecordResponse {
  experiment_id: string;
  state: RunRecordResponseState;
  call_id: string | null;
  created_at: string;
  updated_at: string;
  error: string | null;
  parent_experiment_id: string | null;
  /**
     * @minimum 0
     * @maximum 1000
     */
  revision: number;
  script_snapshot_id: string | null;
}
