/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ScientificCalibration } from './scientificCalibration';
import type { ScientificDecisionOutcome } from './scientificDecisionOutcome';
import type { ScientificQualityCheck } from './scientificQualityCheck';

/**
 * Canonical decision surface shared by scripts, reports, and the UI.
 */
export interface ScientificDecision {
  contract_version?: 'scientific-decision.v1';
  outcome: ScientificDecisionOutcome;
  calibration: ScientificCalibration;
  /**
     * @minLength 1
     * @maxLength 1000
     */
  scope: string;
  /**
     * @minLength 1
     * @maxLength 1000
     */
  headline: string;
  /** @maxItems 64 */
  supported_claims?: string[];
  /**
     * @minItems 1
     * @maxItems 64
     */
  limitations: string[];
  /** @maxItems 64 */
  quality_checks?: ScientificQualityCheck[];
}
