/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ScientificQualityCheckStatus } from './scientificQualityCheckStatus';

export interface ScientificQualityCheck {
  /**
     * @minLength 1
     * @maxLength 160
     */
  label: string;
  status: ScientificQualityCheckStatus;
  value: string | number;
  /**
     * @minLength 1
     * @maxLength 80
     */
  unit: string;
  /**
     * @minLength 1
     * @maxLength 500
     */
  criterion: string;
}
