/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ScientificCalibrationStatus } from './scientificCalibrationStatus';

export interface ScientificCalibration {
  status: ScientificCalibrationStatus;
  /** @minimum 0 */
  accepted_case_count?: number;
  /** @minimum 0 */
  minimum_case_count?: number;
}
