/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ScientificDecisionOutcome = typeof ScientificDecisionOutcome[keyof typeof ScientificDecisionOutcome];


export const ScientificDecisionOutcome = {
  VALIDATED: 'VALIDATED',
  REVIEW: 'REVIEW',
  BLOCKED: 'BLOCKED',
} as const;
