/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ScientificCalibrationStatus = typeof ScientificCalibrationStatus[keyof typeof ScientificCalibrationStatus];


export const ScientificCalibrationStatus = {
  CALIBRATED: 'CALIBRATED',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
} as const;
