/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SweepApplyTransform = typeof SweepApplyTransform[keyof typeof SweepApplyTransform];


export const SweepApplyTransform = {
  identity: 'identity',
  ratio_to_reference: 'ratio_to_reference',
  cubic_ratio_to_reference: 'cubic_ratio_to_reference',
  scale_vector: 'scale_vector',
} as const;
