/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SweepGrid } from './sweepGrid';

export interface SweepCoordinate {
  /**
     * @minLength 1
     * @maxLength 100
     * @pattern ^[A-Za-z][A-Za-z0-9_]*$
     */
  name: string;
  /**
     * @minLength 1
     * @maxLength 160
     */
  label: string;
  /** @maxLength 30 */
  unit?: string;
  grid: SweepGrid;
}
