/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { NVTResult } from './nVTResult';
import type { PKAResult } from './pKAResult';
import type { RelaxResult } from './relaxResult';
import type { SinglePointResult } from './singlePointResult';
import type { SweepPointResultSimulationParams } from './sweepPointResultSimulationParams';
import type { SweepPointResultStatus } from './sweepPointResultStatus';

export interface SweepPointResult {
  /**
     * @minLength 1
     * @maxLength 100
     * @pattern ^[A-Za-z0-9][A-Za-z0-9_-]*$
     */
  id: string;
  /** @minimum 0 */
  index: number;
  value: number;
  applied_value: number | number[];
  simulation_params: SweepPointResultSimulationParams;
  status: SweepPointResultStatus;
  /** @maxItems 100 */
  ensemble?: (PKAResult | RelaxResult | SinglePointResult | NVTResult)[];
  error?: string | null;
}
