/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface SweepResultsReference {
  contract_version?: 'sweep-results-reference.v1';
  /** @pattern ^[A-Za-z0-9][A-Za-z0-9_-]*_sweeps\.json$ */
  artifact_path: string;
  /** @pattern ^[a-f0-9]{64}$ */
  sha256: string;
  /**
     * @minimum 1
     * @maximum 128
     */
  sweep_count: number;
}
