/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SweepResultsArtifactResults } from './sweepResultsArtifactResults';

export interface SweepResultsArtifact {
  contract_version?: 'sweep-results.v1';
  experiment_id: string;
  results: SweepResultsArtifactResults;
}
