/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SweepApply } from './sweepApply';
import type { SweepCoordinate } from './sweepCoordinate';
import type { SweepPointResult } from './sweepPointResult';

export interface SweepResult {
  contract_version?: 'sweep-result.v1';
  coordinate: SweepCoordinate;
  apply: SweepApply;
  /**
     * @minItems 1
     * @maxItems 1000
     */
  points: SweepPointResult[];
}
