/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SweepApplyTransform } from './sweepApplyTransform';

export interface SweepApply {
  /**
     * @minLength 1
     * @maxLength 100
     * @pattern ^[A-Za-z][A-Za-z0-9_]*(?:\.(?:[A-Za-z][A-Za-z0-9_]*|\d+))*$
     */
  target: string;
  transform?: SweepApplyTransform;
  reference?: number | null;
  vector?: number[] | null;
}
