/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TableVisualizationRowsItem = {[key: string]: string | number | boolean | null};
