/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TableColumn } from './tableColumn';
import type { TableVisualizationRowsItem } from './tableVisualizationRowsItem';

export interface TableVisualization {
  /**
     * @minLength 1
     * @maxLength 100
     * @pattern ^[A-Za-z0-9][A-Za-z0-9_-]*$
     */
  id: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  title: string;
  description?: string | null;
  source_node?: string | null;
  kind?: 'table.v1';
  /**
     * @minItems 1
     * @maxItems 50
     */
  columns: TableColumn[];
  /** @maxItems 10000 */
  rows: TableVisualizationRowsItem[];
}
