/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AtomisticVisualization } from './atomisticVisualization';
import type { ChartVisualization } from './chartVisualization';
import type { ImageVisualization } from './imageVisualization';
import type { TableVisualization } from './tableVisualization';

export interface VisualizationCatalog {
  contract_version?: 'v1';
  experiment_id: string;
  /** @maxItems 10000 */
  visualizations?: (AtomisticVisualization | ChartVisualization | TableVisualization | ImageVisualization)[];
}
