/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface VisualizationCatalogReference {
  contract_version?: 'catalog-reference.v1';
  /** @pattern ^[A-Za-z0-9][A-Za-z0-9_-]*_visualizations\.json$ */
  artifact_path: string;
  /** @pattern ^[a-f0-9]{64}$ */
  sha256: string;
  /**
     * @minimum 0
     * @maximum 10000
     */
  visualization_count: number;
}
