/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteExperimentResponse,
  ExperimentBundleResponse,
  ExperimentSpec,
  HTTPValidationError,
  HealthResponse,
  ReportResponse,
  RunRecordResponse,
  SweepResultsArtifact,
  VisualizationCatalog
} from '../model';

import { fetcher } from '.././fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getHealthcheckUrl = () => {




  return `/api/healthz`
}

/**
 * @summary Healthcheck
 */
export const healthcheck = async ( options?: RequestInit): Promise<HealthResponse> => {

  return fetcher<HealthResponse>(getHealthcheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthcheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthcheckQueryOptions = <TData = Awaited<ReturnType<typeof healthcheck>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthcheck>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthcheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthcheck>>> = ({ signal }) => healthcheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthcheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthcheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthcheck>>>
export type HealthcheckQueryError = unknown


export function useHealthcheck<TData = Awaited<ReturnType<typeof healthcheck>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthcheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthcheck>>,
          TError,
          Awaited<ReturnType<typeof healthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthcheck<TData = Awaited<ReturnType<typeof healthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthcheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthcheck>>,
          TError,
          Awaited<ReturnType<typeof healthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthcheck<TData = Awaited<ReturnType<typeof healthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthcheck>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Healthcheck
 */

export function useHealthcheck<TData = Awaited<ReturnType<typeof healthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthcheck>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthcheckQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getListRunsUrl = () => {




  return `/api/runs`
}

/**
 * @summary List Runs
 */
export const listRuns = async ( options?: RequestInit): Promise<RunRecordResponse[]> => {

  return fetcher<RunRecordResponse[]>(getListRunsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListRunsQueryKey = () => {
    return [
    `/api/runs`
    ] as const;
    }


export const getListRunsQueryOptions = <TData = Awaited<ReturnType<typeof listRuns>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRuns>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRunsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRuns>>> = ({ signal }) => listRuns({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRuns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRunsQueryResult = NonNullable<Awaited<ReturnType<typeof listRuns>>>
export type ListRunsQueryError = unknown


export function useListRuns<TData = Awaited<ReturnType<typeof listRuns>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRuns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRuns>>,
          TError,
          Awaited<ReturnType<typeof listRuns>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRuns<TData = Awaited<ReturnType<typeof listRuns>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRuns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRuns>>,
          TError,
          Awaited<ReturnType<typeof listRuns>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRuns<TData = Awaited<ReturnType<typeof listRuns>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRuns>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Runs
 */

export function useListRuns<TData = Awaited<ReturnType<typeof listRuns>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRuns>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRunsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetRunUrl = (id: string,) => {




  return `/api/runs/${id}`
}

/**
 * @summary Get Run
 */
export const getRun = async (id: string, options?: RequestInit): Promise<RunRecordResponse> => {

  return fetcher<RunRecordResponse>(getGetRunUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetRunQueryKey = (id: string,) => {
    return [
    `/api/runs/${id}`
    ] as const;
    }


export const getGetRunQueryOptions = <TData = Awaited<ReturnType<typeof getRun>>, TError = HTTPValidationError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRun>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRunQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRun>>> = ({ signal }) => getRun(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRun>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRunQueryResult = NonNullable<Awaited<ReturnType<typeof getRun>>>
export type GetRunQueryError = HTTPValidationError


export function useGetRun<TData = Awaited<ReturnType<typeof getRun>>, TError = HTTPValidationError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRun>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRun>>,
          TError,
          Awaited<ReturnType<typeof getRun>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRun<TData = Awaited<ReturnType<typeof getRun>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRun>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRun>>,
          TError,
          Awaited<ReturnType<typeof getRun>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRun<TData = Awaited<ReturnType<typeof getRun>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRun>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Run
 */

export function useGetRun<TData = Awaited<ReturnType<typeof getRun>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRun>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRunQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateExperimentUrl = () => {




  return `/api/experiments`
}

/**
 * @summary Submit Experiment
 */
export const createExperiment = async (experimentSpec: ExperimentSpec, options?: RequestInit): Promise<RunRecordResponse> => {

  return fetcher<RunRecordResponse>(getCreateExperimentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(experimentSpec)
  }
);}





export const getCreateExperimentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createExperiment>>, TError,{data: ExperimentSpec}, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof createExperiment>>, TError,{data: ExperimentSpec}, TContext> => {

const mutationKey = ['createExperiment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createExperiment>>, {data: ExperimentSpec}> = (props) => {
          const {data} = props ?? {};

          return  createExperiment(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateExperimentMutationResult = NonNullable<Awaited<ReturnType<typeof createExperiment>>>
    export type CreateExperimentMutationBody = ExperimentSpec
    export type CreateExperimentMutationError = HTTPValidationError

    /**
 * @summary Submit Experiment
 */
export const useCreateExperiment = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createExperiment>>, TError,{data: ExperimentSpec}, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createExperiment>>,
        TError,
        {data: ExperimentSpec},
        TContext
      > => {
      return useMutation(getCreateExperimentMutationOptions(options), queryClient);
    }
    export const getRerunExperimentUrl = (id: string,) => {




  return `/api/experiments/${id}/rerun`
}

/**
 * @summary Rerun Experiment
 */
export const rerunExperiment = async (id: string, options?: RequestInit): Promise<RunRecordResponse> => {

  return fetcher<RunRecordResponse>(getRerunExperimentUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getRerunExperimentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rerunExperiment>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof rerunExperiment>>, TError,{id: string}, TContext> => {

const mutationKey = ['rerunExperiment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rerunExperiment>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  rerunExperiment(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RerunExperimentMutationResult = NonNullable<Awaited<ReturnType<typeof rerunExperiment>>>

    export type RerunExperimentMutationError = HTTPValidationError

    /**
 * @summary Rerun Experiment
 */
export const useRerunExperiment = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rerunExperiment>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rerunExperiment>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getRerunExperimentMutationOptions(options), queryClient);
    }
    export const getDeleteExperimentUrl = (id: string,) => {




  return `/api/experiments/${id}`
}

/**
 * @summary Delete Experiment
 */
export const deleteExperiment = async (id: string, options?: RequestInit): Promise<DeleteExperimentResponse> => {

  return fetcher<DeleteExperimentResponse>(getDeleteExperimentUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteExperimentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteExperiment>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteExperiment>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteExperiment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteExperiment>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteExperiment(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteExperimentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteExperiment>>>

    export type DeleteExperimentMutationError = HTTPValidationError

    /**
 * @summary Delete Experiment
 */
export const useDeleteExperiment = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteExperiment>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteExperiment>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteExperimentMutationOptions(options), queryClient);
    }
    export const getGetExperimentUrl = (id: string,) => {




  return `/api/experiments/${id}`
}

/**
 * @summary Get Experiment
 */
export const getExperiment = async (id: string, options?: RequestInit): Promise<ExperimentBundleResponse> => {

  return fetcher<ExperimentBundleResponse>(getGetExperimentUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetExperimentQueryKey = (id: string,) => {
    return [
    `/api/experiments/${id}`
    ] as const;
    }


export const getGetExperimentQueryOptions = <TData = Awaited<ReturnType<typeof getExperiment>>, TError = HTTPValidationError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExperiment>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExperimentQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExperiment>>> = ({ signal }) => getExperiment(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExperiment>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExperimentQueryResult = NonNullable<Awaited<ReturnType<typeof getExperiment>>>
export type GetExperimentQueryError = HTTPValidationError


export function useGetExperiment<TData = Awaited<ReturnType<typeof getExperiment>>, TError = HTTPValidationError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExperiment>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExperiment>>,
          TError,
          Awaited<ReturnType<typeof getExperiment>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExperiment<TData = Awaited<ReturnType<typeof getExperiment>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExperiment>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExperiment>>,
          TError,
          Awaited<ReturnType<typeof getExperiment>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExperiment<TData = Awaited<ReturnType<typeof getExperiment>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExperiment>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Experiment
 */

export function useGetExperiment<TData = Awaited<ReturnType<typeof getExperiment>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExperiment>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExperimentQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetReportUrl = (id: string,) => {




  return `/api/experiments/${id}/report`
}

/**
 * @summary Get Report
 */
export const getReport = async (id: string, options?: RequestInit): Promise<ReportResponse> => {

  return fetcher<ReportResponse>(getGetReportUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetReportQueryKey = (id: string,) => {
    return [
    `/api/experiments/${id}/report`
    ] as const;
    }


export const getGetReportQueryOptions = <TData = Awaited<ReturnType<typeof getReport>>, TError = HTTPValidationError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReportQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReport>>> = ({ signal }) => getReport(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReportQueryResult = NonNullable<Awaited<ReturnType<typeof getReport>>>
export type GetReportQueryError = HTTPValidationError


export function useGetReport<TData = Awaited<ReturnType<typeof getReport>>, TError = HTTPValidationError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReport>>,
          TError,
          Awaited<ReturnType<typeof getReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReport<TData = Awaited<ReturnType<typeof getReport>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReport>>,
          TError,
          Awaited<ReturnType<typeof getReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReport<TData = Awaited<ReturnType<typeof getReport>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Report
 */

export function useGetReport<TData = Awaited<ReturnType<typeof getReport>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReportQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetVisualizationCatalogUrl = (id: string,) => {




  return `/api/experiments/${id}/visualizations`
}

/**
 * @summary Get Visualizations
 */
export const getVisualizationCatalog = async (id: string, options?: RequestInit): Promise<VisualizationCatalog> => {

  return fetcher<VisualizationCatalog>(getGetVisualizationCatalogUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetVisualizationCatalogQueryKey = (id: string,) => {
    return [
    `/api/experiments/${id}/visualizations`
    ] as const;
    }


export const getGetVisualizationCatalogQueryOptions = <TData = Awaited<ReturnType<typeof getVisualizationCatalog>>, TError = HTTPValidationError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVisualizationCatalog>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVisualizationCatalogQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVisualizationCatalog>>> = ({ signal }) => getVisualizationCatalog(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVisualizationCatalog>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVisualizationCatalogQueryResult = NonNullable<Awaited<ReturnType<typeof getVisualizationCatalog>>>
export type GetVisualizationCatalogQueryError = HTTPValidationError


export function useGetVisualizationCatalog<TData = Awaited<ReturnType<typeof getVisualizationCatalog>>, TError = HTTPValidationError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVisualizationCatalog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVisualizationCatalog>>,
          TError,
          Awaited<ReturnType<typeof getVisualizationCatalog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVisualizationCatalog<TData = Awaited<ReturnType<typeof getVisualizationCatalog>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVisualizationCatalog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVisualizationCatalog>>,
          TError,
          Awaited<ReturnType<typeof getVisualizationCatalog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVisualizationCatalog<TData = Awaited<ReturnType<typeof getVisualizationCatalog>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVisualizationCatalog>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Visualizations
 */

export function useGetVisualizationCatalog<TData = Awaited<ReturnType<typeof getVisualizationCatalog>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVisualizationCatalog>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVisualizationCatalogQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetSweepResultsUrl = (id: string,) => {




  return `/api/experiments/${id}/sweeps`
}

/**
 * @summary Get Sweep Results
 */
export const getSweepResults = async (id: string, options?: RequestInit): Promise<SweepResultsArtifact> => {

  return fetcher<SweepResultsArtifact>(getGetSweepResultsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSweepResultsQueryKey = (id: string,) => {
    return [
    `/api/experiments/${id}/sweeps`
    ] as const;
    }


export const getGetSweepResultsQueryOptions = <TData = Awaited<ReturnType<typeof getSweepResults>>, TError = HTTPValidationError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSweepResults>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSweepResultsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSweepResults>>> = ({ signal }) => getSweepResults(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSweepResults>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSweepResultsQueryResult = NonNullable<Awaited<ReturnType<typeof getSweepResults>>>
export type GetSweepResultsQueryError = HTTPValidationError


export function useGetSweepResults<TData = Awaited<ReturnType<typeof getSweepResults>>, TError = HTTPValidationError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSweepResults>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSweepResults>>,
          TError,
          Awaited<ReturnType<typeof getSweepResults>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSweepResults<TData = Awaited<ReturnType<typeof getSweepResults>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSweepResults>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSweepResults>>,
          TError,
          Awaited<ReturnType<typeof getSweepResults>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSweepResults<TData = Awaited<ReturnType<typeof getSweepResults>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSweepResults>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Sweep Results
 */

export function useGetSweepResults<TData = Awaited<ReturnType<typeof getSweepResults>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSweepResults>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSweepResultsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetVisualizationArtifactUrl = (id: string,
    artifactPath: string,) => {




  return `/api/experiments/${id}/artifacts/${artifactPath}`
}

/**
 * @summary Get Visualization Artifact
 */
export const getVisualizationArtifact = async (id: string,
    artifactPath: string, options?: RequestInit): Promise<Blob> => {

  return fetcher<Blob>(getGetVisualizationArtifactUrl(id,artifactPath),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetVisualizationArtifactQueryKey = (id: string,
    artifactPath: string,) => {
    return [
    `/api/experiments/${id}/artifacts/${artifactPath}`
    ] as const;
    }


export const getGetVisualizationArtifactQueryOptions = <TData = Awaited<ReturnType<typeof getVisualizationArtifact>>, TError = HTTPValidationError>(id: string,
    artifactPath: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVisualizationArtifact>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVisualizationArtifactQueryKey(id,artifactPath);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVisualizationArtifact>>> = ({ signal }) => getVisualizationArtifact(id,artifactPath, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && artifactPath !== null && artifactPath !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVisualizationArtifact>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVisualizationArtifactQueryResult = NonNullable<Awaited<ReturnType<typeof getVisualizationArtifact>>>
export type GetVisualizationArtifactQueryError = HTTPValidationError


export function useGetVisualizationArtifact<TData = Awaited<ReturnType<typeof getVisualizationArtifact>>, TError = HTTPValidationError>(
 id: string,
    artifactPath: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVisualizationArtifact>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVisualizationArtifact>>,
          TError,
          Awaited<ReturnType<typeof getVisualizationArtifact>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVisualizationArtifact<TData = Awaited<ReturnType<typeof getVisualizationArtifact>>, TError = HTTPValidationError>(
 id: string,
    artifactPath: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVisualizationArtifact>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVisualizationArtifact>>,
          TError,
          Awaited<ReturnType<typeof getVisualizationArtifact>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVisualizationArtifact<TData = Awaited<ReturnType<typeof getVisualizationArtifact>>, TError = HTTPValidationError>(
 id: string,
    artifactPath: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVisualizationArtifact>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Visualization Artifact
 */

export function useGetVisualizationArtifact<TData = Awaited<ReturnType<typeof getVisualizationArtifact>>, TError = HTTPValidationError>(
 id: string,
    artifactPath: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVisualizationArtifact>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVisualizationArtifactQueryOptions(id,artifactPath,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






