"""Shared local and Modal-volume locations for editable SCRIPT sources."""

from __future__ import annotations

import hashlib
import io
import os
from dataclasses import dataclass
from pathlib import Path

from modal.exception import AlreadyExistsError, ConflictError

SCRIPT_SOURCE_VOLUME_NAME = "atomforge-script-source-v1"
SCRIPT_SOURCE_MOUNT = "/atomforge-scripts"
SCRIPT_SNAPSHOT_DIR = "snapshots"
LOCAL_SCRIPT_ROOT = Path(__file__).resolve().parents[1] / "node_scripts"


@dataclass(frozen=True, slots=True)
class ScriptSnapshotFile:
    """One immutable source file captured for a SCRIPT snapshot."""

    relative_path: str
    content: bytes


@dataclass(frozen=True, slots=True)
class ScriptSnapshot:
    """A content-addressed snapshot and the exact bytes it identifies."""

    snapshot_id: str
    files: tuple[ScriptSnapshotFile, ...]


def script_root(snapshot_id: str | None = None) -> Path:
    """Return the active SCRIPT source root for local or remote execution."""
    configured = os.environ.get("ATOMFORGE_SCRIPT_ROOT")
    root = Path(configured) if configured else LOCAL_SCRIPT_ROOT
    if snapshot_id:
        return root / SCRIPT_SNAPSHOT_DIR / snapshot_id
    return root


def _source_files(root: Path) -> list[Path]:
    """Return only executable source files, excluding caches and generated bytecode."""
    return sorted(path for path in root.rglob("*.py") if "__pycache__" not in path.parts)


def script_snapshot_id(source_root: Path | None = None) -> str:
    """Hash the complete relative-path/content identity of the local SCRIPT tree."""
    return capture_script_snapshot(source_root).snapshot_id


def capture_script_snapshot(source_root: Path | None = None) -> ScriptSnapshot:
    """Capture source bytes once and derive every snapshot artifact from them."""

    root = (source_root or LOCAL_SCRIPT_ROOT).resolve()
    if not root.is_dir():
        raise ValueError(f"SCRIPT source root does not exist: {root}")
    digest = hashlib.sha256()
    source_paths = _source_files(root)
    if not source_paths:
        raise ValueError(f"SCRIPT source root contains no Python files: {root}")
    files: list[ScriptSnapshotFile] = []
    for path in source_paths:
        relative_path = path.relative_to(root).as_posix()
        relative = relative_path.encode()
        content = path.read_bytes()
        digest.update(len(relative).to_bytes(8, "big"))
        digest.update(relative)
        digest.update(len(content).to_bytes(8, "big"))
        digest.update(content)
        files.append(
            ScriptSnapshotFile(
                relative_path=relative_path,
                content=content,
            )
        )

    snapshot_id = digest.hexdigest()
    return ScriptSnapshot(snapshot_id=snapshot_id, files=tuple(files))


async def _upload_snapshot(volume, snapshot: ScriptSnapshot, *, force: bool) -> None:
    # Batch-upload paths are relative to the volume root. The mount prefix is
    # added only when the volume is mounted in a worker container.
    remote_root = f"{SCRIPT_SNAPSHOT_DIR}/{snapshot.snapshot_id}"
    async with volume.batch_upload(force=force) as batch:
        # Keep captured buffers alive until Modal commits the batch.
        payloads = [io.BytesIO(item.content) for item in snapshot.files]
        for item, payload in zip(snapshot.files, payloads, strict=True):
            batch.put_file(payload, f"{remote_root}/{item.relative_path}")


async def sync_script_sources(volume, *, source_root: Path | None = None) -> str:
    """Publish an immutable, content-addressed SCRIPT snapshot and return its ID."""
    snapshot = capture_script_snapshot(source_root)
    try:
        # The normal path refuses to overwrite an already-published snapshot.
        await _upload_snapshot(volume, snapshot, force=False)
    except (AlreadyExistsError, ConflictError, FileExistsError):
        # A previous upload may have created the same content-addressed path
        # before failing during commit. Repair it with the exact same captured
        # bytes; a changed source tree cannot produce this snapshot ID.
        await _upload_snapshot(volume, snapshot, force=True)
    return snapshot.snapshot_id
